title: SaBa Art Gallery
description: A showcase of unique fine art pieces by SaBa, reflecting personal expression and artistic vision.
baseurl: ""       
url: "https://sabaartgallery.com"   

# theme: minima

collections:
  artworks:
    output: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
